/**
 * Reads the logo asset files and generates a TypeScript module
 * that exports them as string constants. Run this before
 * `bun build --compile` so the assets are baked into the binary.
 *
 * Usage: bun run scripts/embed-assets.ts
 */
import { readFileSync, writeFileSync } from "fs"
import { resolve } from "path"

const ASSETS_DIR = resolve(import.meta.dir, "../../odinslist/assets/Logos")
const OUT_FILE = resolve(import.meta.dir, "../src/embeddedAssets.ts")

const eyeLogo = readFileSync(resolve(ASSETS_DIR, "eye_logo_ansi.txt"), "utf-8").trimEnd()
const textLogo = readFileSync(resolve(ASSETS_DIR, "text_logo_anscii.txt"), "utf-8").trim()

const eyeLogoB64 = Buffer.from(eyeLogo, "utf-8").toString("base64")
const textLogoB64 = Buffer.from(textLogo, "utf-8").toString("base64")

const output = `// Auto-generated by scripts/embed-assets.ts — do not edit manually
const decode = (b64: string) => Buffer.from(b64, "base64").toString("utf-8")

export const EYE_LOGO_RAW: string = decode(
  "${eyeLogoB64}"
)

export const TEXT_LOGO_RAW: string = decode(
  "${textLogoB64}"
)
`

writeFileSync(OUT_FILE, output, "utf-8")
console.log(`Wrote embedded assets to ${OUT_FILE}`)
